# group_vars/all.yml
k8s_version: "1.30"
pod_network_cidr: "10.244.0.0/16" # Flannel default
kubernetes_rpm_repo: "https://pkgs.k8s.io/core:/stable:/v1.30/rpm/"
kubernetes_rpm_key_url: "https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key"
